# Generated by Django 5.0 on 2024-01-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=60)),
                ('product_category', models.CharField(max_length=60)),
                ('product_price', models.FloatField()),
                ('product_expiry_date', models.DateField()),
                ('product_manufacturing_date', models.DateField()),
                ('product_HSN_no', models.CharField(max_length=8)),
                ('product_quantity', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['product_category'],
            },
        ),
    ]
